name: Check pxt.json

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v1

    - name: Validate / fix pxt.json
      run: node ./.github/workflows/json-check.js

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        commit-message: Removing missing files from pxt.json
        title: '🐛 missing files listed in pxt.json 🐛'