name: MakeCode

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: キャッシュをセットアップ
        uses: actions/cache@v3
        id: node_cache_id
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-npm2-${{ hashFiles('**/package-lock.json') }}
          
      - name: npm install pxt
        run: npm install -g pxt

      - name: npm install
        if: ${{ steps.node_cache_id.outputs.cache-hit != 'true' }}
        run: npm install

      - name: make pkt.json
        run: |
          echo "{\"targetdir\": \"pxt-arcade\"}" > node_modules/pxtcli.json
          cat node_modules/pxtcli.json
          
      - name: pxt install
        run: pxt install
        env:
          CI: true

      - name: pxt build
        run: pxt build --cloud
        env:
          CI: true
